# Generated by Django 5.2.4 on 2025-08-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0008_alter_studentid_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='date_of_rank_generation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_rank_generation')},
        ),
    ]
